/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlbumsSlugRouteImport } from './routes/albums.$slug'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppPunchListRouteImport } from './routes/_authenticated/app.punch-list'
import { Route as AuthenticatedAppInspectionsRouteImport } from './routes/_authenticated/app.inspections'
import { Route as AuthenticatedAppFinancialsRouteImport } from './routes/_authenticated/app.financials'
import { Route as AuthenticatedAppDirectoryRouteImport } from './routes/_authenticated/app.directory'
import { Route as AuthenticatedAppDailyLogsRouteImport } from './routes/_authenticated/app.daily-logs'
import { Route as AuthenticatedAppControlsRouteImport } from './routes/_authenticated/app.controls'
import { Route as AuthenticatedAppJobsIndexRouteImport } from './routes/_authenticated/app.jobs.index'
import { Route as AuthenticatedAppDocumentsIndexRouteImport } from './routes/_authenticated/app.documents.index'
import { Route as AuthenticatedAppJobsJobIdRouteImport } from './routes/_authenticated/app.jobs.$jobId'
import { Route as AuthenticatedAppDocumentsDocIdRouteImport } from './routes/_authenticated/app.documents.$docId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsSlugRoute = AlbumsSlugRouteImport.update({
  id: '/albums/$slug',
  path: '/albums/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPunchListRoute =
  AuthenticatedAppPunchListRouteImport.update({
    id: '/punch-list',
    path: '/punch-list',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInspectionsRoute =
  AuthenticatedAppInspectionsRouteImport.update({
    id: '/inspections',
    path: '/inspections',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFinancialsRoute =
  AuthenticatedAppFinancialsRouteImport.update({
    id: '/financials',
    path: '/financials',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDirectoryRoute =
  AuthenticatedAppDirectoryRouteImport.update({
    id: '/directory',
    path: '/directory',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDailyLogsRoute =
  AuthenticatedAppDailyLogsRouteImport.update({
    id: '/daily-logs',
    path: '/daily-logs',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppControlsRoute =
  AuthenticatedAppControlsRouteImport.update({
    id: '/controls',
    path: '/controls',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppJobsIndexRoute =
  AuthenticatedAppJobsIndexRouteImport.update({
    id: '/jobs/',
    path: '/jobs/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDocumentsIndexRoute =
  AuthenticatedAppDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppJobsJobIdRoute =
  AuthenticatedAppJobsJobIdRouteImport.update({
    id: '/jobs/$jobId',
    path: '/jobs/$jobId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDocumentsDocIdRoute =
  AuthenticatedAppDocumentsDocIdRouteImport.update({
    id: '/documents/$docId',
    path: '/documents/$docId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/albums/$slug': typeof AlbumsSlugRoute
  '/app/controls': typeof AuthenticatedAppControlsRoute
  '/app/daily-logs': typeof AuthenticatedAppDailyLogsRoute
  '/app/directory': typeof AuthenticatedAppDirectoryRoute
  '/app/financials': typeof AuthenticatedAppFinancialsRoute
  '/app/inspections': typeof AuthenticatedAppInspectionsRoute
  '/app/punch-list': typeof AuthenticatedAppPunchListRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/documents/$docId': typeof AuthenticatedAppDocumentsDocIdRoute
  '/app/jobs/$jobId': typeof AuthenticatedAppJobsJobIdRoute
  '/app/documents/': typeof AuthenticatedAppDocumentsIndexRoute
  '/app/jobs/': typeof AuthenticatedAppJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/albums/$slug': typeof AlbumsSlugRoute
  '/app/controls': typeof AuthenticatedAppControlsRoute
  '/app/daily-logs': typeof AuthenticatedAppDailyLogsRoute
  '/app/directory': typeof AuthenticatedAppDirectoryRoute
  '/app/financials': typeof AuthenticatedAppFinancialsRoute
  '/app/inspections': typeof AuthenticatedAppInspectionsRoute
  '/app/punch-list': typeof AuthenticatedAppPunchListRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/documents/$docId': typeof AuthenticatedAppDocumentsDocIdRoute
  '/app/jobs/$jobId': typeof AuthenticatedAppJobsJobIdRoute
  '/app/documents': typeof AuthenticatedAppDocumentsIndexRoute
  '/app/jobs': typeof AuthenticatedAppJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/albums/$slug': typeof AlbumsSlugRoute
  '/_authenticated/app/controls': typeof AuthenticatedAppControlsRoute
  '/_authenticated/app/daily-logs': typeof AuthenticatedAppDailyLogsRoute
  '/_authenticated/app/directory': typeof AuthenticatedAppDirectoryRoute
  '/_authenticated/app/financials': typeof AuthenticatedAppFinancialsRoute
  '/_authenticated/app/inspections': typeof AuthenticatedAppInspectionsRoute
  '/_authenticated/app/punch-list': typeof AuthenticatedAppPunchListRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/documents/$docId': typeof AuthenticatedAppDocumentsDocIdRoute
  '/_authenticated/app/jobs/$jobId': typeof AuthenticatedAppJobsJobIdRoute
  '/_authenticated/app/documents/': typeof AuthenticatedAppDocumentsIndexRoute
  '/_authenticated/app/jobs/': typeof AuthenticatedAppJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/app'
    | '/albums/$slug'
    | '/app/controls'
    | '/app/daily-logs'
    | '/app/directory'
    | '/app/financials'
    | '/app/inspections'
    | '/app/punch-list'
    | '/app/'
    | '/app/documents/$docId'
    | '/app/jobs/$jobId'
    | '/app/documents/'
    | '/app/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/albums/$slug'
    | '/app/controls'
    | '/app/daily-logs'
    | '/app/directory'
    | '/app/financials'
    | '/app/inspections'
    | '/app/punch-list'
    | '/app'
    | '/app/documents/$docId'
    | '/app/jobs/$jobId'
    | '/app/documents'
    | '/app/jobs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/app'
    | '/albums/$slug'
    | '/_authenticated/app/controls'
    | '/_authenticated/app/daily-logs'
    | '/_authenticated/app/directory'
    | '/_authenticated/app/financials'
    | '/_authenticated/app/inspections'
    | '/_authenticated/app/punch-list'
    | '/_authenticated/app/'
    | '/_authenticated/app/documents/$docId'
    | '/_authenticated/app/jobs/$jobId'
    | '/_authenticated/app/documents/'
    | '/_authenticated/app/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AlbumsSlugRoute: typeof AlbumsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$slug': {
      id: '/albums/$slug'
      path: '/albums/$slug'
      fullPath: '/albums/$slug'
      preLoaderRoute: typeof AlbumsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/punch-list': {
      id: '/_authenticated/app/punch-list'
      path: '/punch-list'
      fullPath: '/app/punch-list'
      preLoaderRoute: typeof AuthenticatedAppPunchListRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/inspections': {
      id: '/_authenticated/app/inspections'
      path: '/inspections'
      fullPath: '/app/inspections'
      preLoaderRoute: typeof AuthenticatedAppInspectionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/financials': {
      id: '/_authenticated/app/financials'
      path: '/financials'
      fullPath: '/app/financials'
      preLoaderRoute: typeof AuthenticatedAppFinancialsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/directory': {
      id: '/_authenticated/app/directory'
      path: '/directory'
      fullPath: '/app/directory'
      preLoaderRoute: typeof AuthenticatedAppDirectoryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/daily-logs': {
      id: '/_authenticated/app/daily-logs'
      path: '/daily-logs'
      fullPath: '/app/daily-logs'
      preLoaderRoute: typeof AuthenticatedAppDailyLogsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/controls': {
      id: '/_authenticated/app/controls'
      path: '/controls'
      fullPath: '/app/controls'
      preLoaderRoute: typeof AuthenticatedAppControlsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/jobs/': {
      id: '/_authenticated/app/jobs/'
      path: '/jobs'
      fullPath: '/app/jobs/'
      preLoaderRoute: typeof AuthenticatedAppJobsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/documents/': {
      id: '/_authenticated/app/documents/'
      path: '/documents'
      fullPath: '/app/documents/'
      preLoaderRoute: typeof AuthenticatedAppDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/jobs/$jobId': {
      id: '/_authenticated/app/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/app/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedAppJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/documents/$docId': {
      id: '/_authenticated/app/documents/$docId'
      path: '/documents/$docId'
      fullPath: '/app/documents/$docId'
      preLoaderRoute: typeof AuthenticatedAppDocumentsDocIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppControlsRoute: typeof AuthenticatedAppControlsRoute
  AuthenticatedAppDailyLogsRoute: typeof AuthenticatedAppDailyLogsRoute
  AuthenticatedAppDirectoryRoute: typeof AuthenticatedAppDirectoryRoute
  AuthenticatedAppFinancialsRoute: typeof AuthenticatedAppFinancialsRoute
  AuthenticatedAppInspectionsRoute: typeof AuthenticatedAppInspectionsRoute
  AuthenticatedAppPunchListRoute: typeof AuthenticatedAppPunchListRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppDocumentsDocIdRoute: typeof AuthenticatedAppDocumentsDocIdRoute
  AuthenticatedAppJobsJobIdRoute: typeof AuthenticatedAppJobsJobIdRoute
  AuthenticatedAppDocumentsIndexRoute: typeof AuthenticatedAppDocumentsIndexRoute
  AuthenticatedAppJobsIndexRoute: typeof AuthenticatedAppJobsIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppControlsRoute: AuthenticatedAppControlsRoute,
  AuthenticatedAppDailyLogsRoute: AuthenticatedAppDailyLogsRoute,
  AuthenticatedAppDirectoryRoute: AuthenticatedAppDirectoryRoute,
  AuthenticatedAppFinancialsRoute: AuthenticatedAppFinancialsRoute,
  AuthenticatedAppInspectionsRoute: AuthenticatedAppInspectionsRoute,
  AuthenticatedAppPunchListRoute: AuthenticatedAppPunchListRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppDocumentsDocIdRoute: AuthenticatedAppDocumentsDocIdRoute,
  AuthenticatedAppJobsJobIdRoute: AuthenticatedAppJobsJobIdRoute,
  AuthenticatedAppDocumentsIndexRoute: AuthenticatedAppDocumentsIndexRoute,
  AuthenticatedAppJobsIndexRoute: AuthenticatedAppJobsIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AlbumsSlugRoute: AlbumsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
